{
 "title": "Grafana Dashboards",
 "description": "Grafana Dashboards managed via the Kubernetes Grafana Sidecar",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dashboards",
   "type": "stat",
   "description": "Number of dashboard resources managed",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_grafana_sidecar_resources)"
    }
   ]
  },
  {
   "title": "Dashboard Errors",
   "type": "stat",
   "description": "Number of dashboard resources managed that are in an error state",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_grafana_sidecar_resource_errors)"
    }
   ]
  },
  { "title": "Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Dashboard actions",
   "type": "graph",
   "description": "Create, Update and Delete actions on dashboard resources",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(k8s_grafana_sidecar_created_resources_total[$__interval]))",
     "legendFormat": "Creates"
    },
    {
     "expr": "sum(increase(k8s_grafana_sidecar_deleted_resources_total[$__interval]))",
     "legendFormat": "Deletes"
    },
    {
     "expr": "sum(increase(k8s_grafana_sidecar_updated_resources_total[$__interval]))",
     "legendFormat": "Updates"
    }
   ]
  },
  {
   "title": "Dashboard Errors",
   "type": "graph",
   "description": "Errors occurring when handling dashboard resources",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(k8s_grafana_sidecar_resource_errors[$__interval])) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Dashboard actions (totals)",
   "type": "graph",
   "description": "Create, Update and Delete actions on dashboard resources",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(k8s_grafana_sidecar_created_resources_total)",
     "legendFormat": "Creates"
    },
    {
     "expr": "sum(k8s_grafana_sidecar_deleted_resources_total)",
     "legendFormat": "Deletes"
    },
    {
     "expr": "sum(k8s_grafana_sidecar_updated_resources_total)",
     "legendFormat": "Updates"
    }
   ]
  },
  {
   "title": "Dashboard Errors (totals)",
   "type": "graph",
   "description": "Errors encountered when handling dashboard resources",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(k8s_grafana_sidecar_resource_errors) by (error) ",
     "legendFormat": "{{error}}"
    }
   ]
  }
 ]
}